spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://moonbuddy.cpyvecptwrde.eu-north-1.rds.amazonaws.com:3306/moonbuddy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: moonbuddy
    password: moonbuddy123!
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 621978938737-2dpk9sung4urrh0elrk7fir1c20grf5b.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
#파라미터값 표출
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#  profiles:
#    include: oauth
